### ISSUE TITLE
Z-index either not used or misleading

### ISSUE THREAD

**Issue by SebastianKG** [Zinggi/elm-2d-game#6]
When using functions like `shapeZ`, `spriteZ`, or any of the more complicated provided functions with a `Float3` position, the Z-order (where sprite layering is determined by the last number in the `Float3` tuple) is not respected -- or, it may work in a confusing way.

**Expected Behaviour:** swapping of non-equal Z-coordinates of overlapping sprites should swap their layering.
**Current Behaviour:** no change is seen when Z-coordinates are swapped.

I've created a simple example using `shapeZ` on Ellie, which can be found [here](https://ellie-app.com/6LY34Rhvrb3a1).

**Comment by Zinggi** [comment]
@SebastianKG Thanks for reporting, I'll investigate when I have some time

**Comment by Zinggi** [comment]
@SebastianKG This has been fixed in https://github.com/Zinggi/elm-2d-game/pull/8
I'll publish a new version soon.
Thanks for the helpful ellie, this really helped to quickly find the issue!

EDIT: published!
